// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHm6bZfsTW5Z7TJh0Out-2rKj2_is21oU',
    appId: '1:562726371770:web:1d38834f50641cc574dd83',
    messagingSenderId: '562726371770',
    projectId: 'myapp-a675b',
    authDomain: 'myapp-a675b.firebaseapp.com',
    databaseURL: 'https://myapp-a675b-default-rtdb.firebaseio.com',
    storageBucket: 'myapp-a675b.appspot.com',
    measurementId: 'G-WG5FZF6Y9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDKMxUr4g82JmFDZWvkEoT-kPTVKL3_jU',
    appId: '1:562726371770:android:24209c721bf2050374dd83',
    messagingSenderId: '562726371770',
    projectId: 'myapp-a675b',
    databaseURL: 'https://myapp-a675b-default-rtdb.firebaseio.com',
    storageBucket: 'myapp-a675b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV28wCqRYERxhHUjFrKBJF_UNxgrGlxmo',
    appId: '1:562726371770:ios:70c0c88d06d4571674dd83',
    messagingSenderId: '562726371770',
    projectId: 'myapp-a675b',
    databaseURL: 'https://myapp-a675b-default-rtdb.firebaseio.com',
    storageBucket: 'myapp-a675b.appspot.com',
    iosClientId: '562726371770-8lv9e5p8c29s5sldpqkd3nvgbnqjhbi8.apps.googleusercontent.com',
    iosBundleId: 'com.example.splashscreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV28wCqRYERxhHUjFrKBJF_UNxgrGlxmo',
    appId: '1:562726371770:ios:dc1d536b3bc7a7dd74dd83',
    messagingSenderId: '562726371770',
    projectId: 'myapp-a675b',
    databaseURL: 'https://myapp-a675b-default-rtdb.firebaseio.com',
    storageBucket: 'myapp-a675b.appspot.com',
    iosClientId: '562726371770-bpu5a0hop1s3dc7qp6f73mdb9c079sfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.splashscreen.RunnerTests',
  );
}
